import { MD3LightTheme as DefaultTheme } from "react-native-paper";

export const appTheme = {
  ...DefaultTheme,
  dark: false, 
  version: 3, 
  mode: "adaptive",
  roundness: 8, 

  colors: {
    ...DefaultTheme.colors,
    "primary": "#39BCD9",
  "onPrimary": "rgb(255, 255, 255)",
  "primaryContainer": "#4DDEFE",
  "onPrimaryContainer": "rgb(0, 50, 45)",
  "secondary": "#91E228",
  "onSecondary": "rgb(255, 255, 255)",
  "secondaryContainer": "#91E228",
  "onSecondaryContainer": "rgb(0, 40, 0)",
  "tertiary": "rgb(0, 130, 200)",
  "onTertiary": "rgb(255, 255, 255)",
  "tertiaryContainer": "rgb(180, 240, 255)",
  "onTertiaryContainer": "rgb(0, 50, 80)",
  "error": "rgb(220, 50, 50)",
  "onError": "rgb(255, 255, 255)",
  "errorContainer": "rgb(255, 180, 180)",
  "onErrorContainer": "rgb(80, 0, 0)",
  "background": "rgb(245, 255, 245)",
  "onBackground": "rgb(30, 35, 30)",
  "surface": "rgb(235, 245, 235)",
  "onSurface": "rgb(30, 35, 30)",
  "surfaceVariant": "rgb(200, 240, 230)",
  "onSurfaceVariant": "rgb(50, 70, 65)",
  "outline": "rgb(100, 140, 130)",
  "outlineVariant": "rgb(180, 210, 200)",
  "shadow": "rgb(0, 0, 0)",
  "scrim": "rgb(0, 0, 0)",
  "inverseSurface": "rgb(50, 60, 55)",
  "inverseOnSurface": "rgb(240, 250, 245)",
  "inversePrimary": "rgb(70, 240, 200)",
    "elevation": {
      "level0": "transparent",
      "level1": "rgb(238, 246, 243)",
      "level2": "rgb(230, 241, 238)",
      "level3": "rgb(223, 237, 234)",
      "level4": "rgb(220, 236, 232)",
      "level5": "rgb(215, 233, 229)"
    },
    "surfaceDisabled": "rgba(25, 28, 27, 0.12)",
    "onSurfaceDisabled": "rgba(25, 28, 27, 0.38)",
    "backdrop": "rgba(41, 50, 48, 0.4)"
  },

  fonts: {
    displayLarge: {
      fontFamily: "Roboto-Light",
      letterSpacing: 0,
      fontWeight: "300",
      lineHeight: 64,
      fontSize: 57,
    },
    displayMedium: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 52,
      fontSize: 45,
    },
    displaySmall: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 44,
      fontSize: 36,
    },
    headlineLarge: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 40,
      fontSize: 32,
    },
    headlineMedium: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 36,
      fontSize: 28,
    },
    headlineSmall: {
      fontFamily: "Roboto-Bold",
      letterSpacing: 0,
      fontWeight: "700",
      lineHeight: 32,
      fontSize: 24,
    },
    titleLarge: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0,
      fontWeight: "500",
      lineHeight: 28,
      fontSize: 22,
    },
    titleMedium: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0.15,
      fontWeight: "500",
      lineHeight: 24,
      fontSize: 16,
    },
    titleSmall: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0.1,
      fontWeight: "500",
      lineHeight: 20,
      fontSize: 14,
    },
    labelLarge: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0.1,
      fontWeight: "500",
      lineHeight: 20,
      fontSize: 14,
    },
    labelMedium: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0.15,
      fontWeight: "500",
      lineHeight: 16,
      fontSize: 12,
    },
    labelSmall: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0.1,
      fontWeight: "500",
      lineHeight: 14,
      fontSize: 11,
    },
    bodyLarge: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0.15,
      fontWeight: "400",
      lineHeight: 24,
      fontSize: 16,
    },
    bodyMedium: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0.25,
      fontWeight: "400",
      lineHeight: 20,
      fontSize: 14,
    },
    bodySmall: {
      fontFamily: "Roboto-Regular",
      letterSpacing: 0.4,
      fontWeight: "400",
      lineHeight: 16,
      fontSize: 12,
    },
  },
  animation: {
    scale: 1.0,
  },
  surface: {
      padding: 20,
      margin: 20,
      alignItems: "center",
      justifyContent: "center",
      borderRadius:20,
      backgroundColor: "rgb(235, 245, 235)"
    }
};
